### ISSUE TITLE
Basic source lookup not working properly

### ISSUE THREAD

**Issue by alexfont** [Snorby/snorby#144]
Hi all,

I've an issue with the source lookup functionality, it fails when trying to resolve an ip address.
Looking at production.log, it shows:

Started GET "/events/lookup?address=191.1.85.85" for 172.26.135.109 at 2011-09-27 16:25:48 +0200
  Processing by EventsController#lookup as
  Parameters: {"address"=>"191.1.85.85"}
Rendered events/lookup.html.erb (26.6ms)
Completed   in 315ms

ActionView::Template::Error (getaddrinfo: Name or service not known):
    6:
    7:  <div id='lookup-box-content' class=''>
    8:
    9:          <pre id='whois' class='query-data-content'><%= @lookup.whois %></pre>
    10:
    11:                 <pre id='dns' class='query-data-content' style='display:none;'><%= @lookup.dns %></pre>
    12:
  lib/snorby/lookup.rb:35:in `whois'
  app/views/events/lookup.html.erb:9:in`block in _app_views_events_lookup_html_erb__743274767_96776690__41025452'
  app/helpers/application_helper.rb:130:in `snorby_box'
  app/views/events/lookup.html.erb:1:in`_app_views_events_lookup_html_erb__743274767_96776690__41025452'
  app/controllers/events_controller.rb:176:in `lookup'

...but when I try to make a lookup from the shell in the same box, it works perfectly:

$ nslookup 191.1.85.85

Server:         172.20.10.10
Address:        172.20.10.10#53

85.85.1.191.in-addr.arpa        name = zipi.cartoons.com.

the resolv.conf config is:

search cartoons.com
nameserver 172.20.10.10
nameserver 172.20.10.11
nameserver 172.20.10.12

and the nsswitch.conf:

hosts:          files dns

(for snorby 2.3.9)

any clue??

thanks in advance!
Alex

**Comment by Know1** [comment]
I was having a similar issue with DNS lookups not working.
Turned out there is a problem with Ruby 2.2 and later and changes Config to RbConfig

Getting the Internal Server Error doing Basic Source Lookup
Also Resolver("www.google.com.au") in irb would throw the error
  NameError: uninitialized constant Config

to fix it I edited the <INSTALLDIR>/snorby/Gemfile from
  gem 'net-dns',                     '~> 0.6.1'
to 
  gem 'net-dns',                     '~> 0.8.0'
to force it to use the updated net-dns which works with Ruby 2.2+

Has been running fine since, not sure if this change affects anything else.

**Comment by gehrhorn** [comment]
@Know1 if you send a pull request I can merge it.
