### ISSUE TITLE
Issues connecting Snorby to remote mysql database

### ISSUE THREAD

**Issue by alligatorwine** [Snorby/snorby#365]
Hi, I am a newbie in Snorby/Snort products. 
My environment is composed by 2 CentOS 6.6 servers. The first one runs Snort/Barnyard2/Pulledpork and logs alert on a mysql database. The second one runs Snorby. 
I am quite confused here. 
Now:
Should Snorby connect to the remote database on the Snort machine, or should Snort log alerts remotely to the Snorby local database? 
Somehow, I've been starting to think that Snorby can work only on local databases. 
Any help is really appreciated. 
Thank you very much!
Antonella.

**Comment by charliedrage** [comment]
Hey @alligatorwine 

To answer your question first, yes, Barnyard2 is suppose to connect to the mysql database (or any database for the matter), not Snorby connecting to Barnyard. 

It acts as a client->server relationship.

Not to make you switch or anything, but I constantly had problems with Snort and Barnyard2. I ended up switching to Suricata and Barnyard2 which ended up MUCH easier to setup. A link on my github to my personal site has a tutorial to set it up.

Using something like Oinkmaster instead of pulledpork would be viable too.

**Comment by alligatorwine** [comment]
Thank you so much! By now I have managed to correctly make Barnyard2 send alert to the Snorby database. I can see them growing up in number in the web interface. What kind of problems did you exactly experience with the Snort/Barnyard2/Snorby environment? 
Now I'm trying to optimize my setup (rules and so on) and run Snorby as a service. 
Thank you again.
